---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4881369326-a7WsqBvVcL6JYbH1L4MT5MQtkK5OS9Bx1DTQITH
:access_token_secret: HsFPFPpr2PJcLf0gWn2DUFxiGyAUgsAUGzQ5PHUoPsHwY
